server:
  port: 8083
spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${DB_USER:agrodirecto}
    password: ${DB_PASSWORD:agrodirecto123}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:agrodirecto}
    password: ${RABBITMQ_PASSWORD:agrodirecto123}
management:
  endpoints:
    web:
      exposure:
        include: health,info
