server:
  port: 8083
spring:
  application:
    name: order-service
  datasource:
    url: \
    username: \
    password: \
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:agrodirecto}
    password: ${RABBITMQ_PASSWORD:agrodirecto123}
