server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:

        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/auth/**

        - id: catalog-service
          uri: ${CATALOG_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/categorias/**,/api/productos/**

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/carrito/**,/api/checkout/**,/api/pedidos/**

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/notificaciones/**

        - id: report-service
          uri: ${REPORT_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/report/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
