server:
  port: 8082
spring:
  application:
    name: catalog-service
  datasource:
    url: \
    username: \
    password: \
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
